FROM node:slim

WORKDIR /express-docker
dwad
ENV RUN_TYvada
awdas
COPY package.json ./

RUN npm install
dawdas
COPY 

# Exposing server port
EXPE 5000

# Running npm run start on port 5000
CMD ["npm", "run", "start"]
