name: Dockerfile linting

on:
  push:
    paths:
      - '**/Dockerfile*'

jobs:
  lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find Dockerfiles
        id: find_dockerfiles
        run: |
          echo "name=dockerfiles::$(find . -type f -name 'Dockerfile*')" >> $GITHUB_OUTPUT
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ github.action_output }}
