name: Dockerfile linting

on:
  push:
    paths:
      - '**/Dockerfile*'

jobs:
  lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find Dockerfiles
        id: find_dockerfiles
        run: |
          dockerfiles=""
          while IFS= read -r -d '' file; do
            dockerfiles="$dockerfiles$file "
          done < <(find . -type f -name 'Dockerfile*' -print0)
          echo "dockerfiles=$dockerfiles" >> $GITHUB_ENV
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.dockerfiles }}
