name: Dockerfile linting

on:
  push:
    paths:
      - '**/Dockerfile*'

jobs:
  lint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find Dockerfiles
        id: find_dockerfiles
        run: |
          find . -type f -name 'Dockerfile*' | while read -r file; do
            echo "$file"
          done
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ steps.find_dockerfiles.outputs }}  # Use output from previous step
